

services:


  opamp-server:
    build:
      context: ./opamp-server
    image: local/opamp-server:latest
    container_name: opamp-server
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        apk add --no-cache socat >/dev/null 2>&1 || true
        # ponte externa 0.0.0.0:14320 -> 127.0.0.1:4320 (onde o server está preso)
        socat TCP-LISTEN:14320,fork,reuseaddr TCP:127.0.0.1:4320 &
        exec /usr/local/bin/opamp-server
    ports:
      - "4320:14320"  # OpAMP endpoint
      - "4321:4321"  # UI
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:4321/"]
      interval: 10s
      timeout: 5s
      retries: 20


 